### ISSUE TITLE
Read the file.csv and save the information on a struct.

### ISSUE THREAD

**Issue by edgarN7** [edgarN7/library-system#5]
Testing and trying to find out how to save properly the information from a file.csv on a struct.

**Comment by JandersonCRB** [comment]
@edgarN7 

Notice there is no automated way to do that. You will have to create your own algorithm to parse the file and separate each data you want.

See this: https://www.cplusplus.com/reference/cstring/strtok/

You are gonna have to do it twice, first for separating the lines, and then for separating names from quantities
